# -*- coding: utf-8 -*-
"""add_to_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypUw1I7zu2qDo_2KxdGBHeO16w0t17tO
"""

def main():
  Num1 = input("Enter your First Number: ")  # User Enter first number
  Num1 : int = int(Num1)                     # Number Convert str to int
  Num2 = input("Enter your Second Number: ") # User Enter Second number
  Num2 : int = int(Num2)                     # Number Convert str to int
  Total : int = Num1 + Num2                  # Num1 and Num2 is added and stored in Total Variable
  print(f"The total value of {Num1} + {Num2} is {Total}")  # This will print the total value
if __name__ == '__main__':
    main()