# -*- coding: utf-8 -*-
"""02_agreement_bot.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fuM69LyqRaqYYOKrA8vepNSQ5Y2jGTC
"""

def main():
   Animal = input ("What's your favorite animal?\033[1;3m")
   print(f"\033[0mMy favorite animal is also \033[1;3m{Animal}!")
if __name__ == '__main__':
    main()