# -*- coding: utf-8 -*-
"""03_fahrenheit_to_celsius.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbayDpYQV4hdV4vwt4LwFZuXTNxPtcd2
"""

def main():
    Number_Fahrenheit = float(input("Enter Temperature in Fahrenheit:\033[1;3m "))
    degree_Celcius = (Number_Fahrenheit - 32)* 5.0 / 9.0
    print(f"\033[0mTemperature : {Number_Fahrenheit}F = \033[1;3m{degree_Celcius}C")

if __name__ == '__main__':
    main()