# -*- coding: utf-8 -*-
"""04_how_old_are_they.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-jNalDgVwDUP0HFJgg3ojlJ-7yGdfad
"""

def main():
    Anton : int = 21
    Beth : int = 6 + Anton
    Chen : int = 20 + Beth
    Drew : int = Chen + Anton
    Ethan : int = Chen

    print(f"The age of Anton is {Anton}")
    print(f"The age of Beth is {Beth}")
    print(f"The age of Chen is {Chen}")
    print(f"The age of Drew is {Drew}")
    print(f"The age of Ethan is {Ethan}")


if __name__ == '__main__':
    main()