# -*- coding: utf-8 -*-
"""05_triangle_perimeter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KaNHobxARGzu76n9jf_KNERHs91BUoEc
"""

def main():

  Side1 : float = float(input("\033[0mWhat is the lenght of side 1?\033[1;3m "))
  Side2 : float = float(input("\033[0mWhat is the lenght of side 2?\033[1;3m "))
  Side3 : float = float(input("\033[0mWhat is the lenght of side 3?\033[1;3m "))

  Traingle_Perimeter = (Side1 + Side2 + Side3)
  print(f"\033[0mThe perimeter of the traingle is \033[1;3m{Traingle_Perimeter}")
if __name__ == '__main__':
    main()