# -*- coding: utf-8 -*-
"""06_square_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlvjL7FzM9j3xGCfK9zItH4Z3oA6_4Vs
"""

def main():
    Num_Input : float = float(input("Type a number to see its square:\033[1;3m "))
    Num_Square : float = float(Num_Input ** 2)
    print(f"\033[0mThe Square of \033[1;3m{Num_Input} \033[0mis \033[1;3m{Num_Square}")

if __name__ == '__main__':
    main()