# -*- coding: utf-8 -*-
"""BMI Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kp6K1XPOoyjXxNhge2_BJg1acRtcPU-u
"""
import streamlit as st

st.set_page_config(page_title="BMI Calculator", page_icon="🧮")
st.title("🧮 BMI Calculator")

st.sidebar.header("Enter your details")

name = st.sidebar.text_input("Name", value = "Hamzah")
age = st.sidebar.number_input("Age", min_value = 1, max_value = 100, value = 25)
gender = st.sidebar.selectbox("Gender", options = ["Male", "Female"])

height_cm = st.sidebar.number_input("Height (cm)", min_value = 1, max_value = 300, value = 170)
weight_kg = st.sidebar.number_input("Weight (kg)", min_value = 1, max_value = 300, value = 70)

if st.sidebar.button("Calculate BMI"):
  bmi = weight_kg / ((height_cm / 100) ** 2)

  if bmi < 18.5:
    category = "Underweight"
    color = "🔵"
  elif 18.5 <= bmi < 25:
    category = "Normal weight"
    color = "🟢"
  elif 25 <= bmi < 30:
    category = "Overweight"
    color = "🟠"
  else:
    category = "Obese"
    color = "🔴"

  st.subheader(f"Hello {name} 👋")
  st.write(f"**Age:** {age} | **Gender:** {gender}")
  st.metric(label = "Your BMI", value =f"{bmi:.2f}", delta = category)
  st.success(f"{color} You are categorized as **{category}**.")

  with st.expander("ℹ️ BMI Category Info"):
        st.markdown("""
        - **Underweight**: BMI less than 18.5
        - **Normal weight**: BMI 18.5 – 24.9
        - **Overweight**: BMI 25 – 29.9
        - **Obese**: BMI 30 or greater
        """)
else:
    st.info("👈 Enter your details in the sidebar and click **Calculate BMI**.")


st.markdown("---")
st.markdown("Made By Zohaib Memon ❤️")