# -*- coding: utf-8 -*-
"""Countdown Time.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVKn63QPVCfSrM12ExnVCykxegFsFd8O
"""

import time

def count_time(hrs, mins, secs):
    total = hrs * 3600 + mins * 60 + secs
    while total > 0:
        hours, remainder = divmod(total, 3600)
        minutes, seconds = divmod(remainder, 60)

        timer = f"{hours:02d}:{minutes:02d}:{seconds:02d}"
        print(timer)
        time.sleep(1)
        total -= 1

    print("Time's Up!")


def main():
  try:
    hrs = int(input("Enter hours: "))
    min = int(input("Enter minutes: "))
    sec = int(input("Enter seconds: "))
    count_time(hrs, min, sec)
  except ValueError:
    print("Invalid input. Please enter valid numbers.")
if __name__ == "__main__":
  main()