# -*- coding: utf-8 -*-
"""Guess the Number Game (computer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KcHMXaiOP9ezDAKejV5ZuATMJ7vn28G
"""

import random

def computer_guess():
    print("🧠 Let me guess your number between 1 and 100!")
    print("Think of a number, and I'll try to guess it. Let me know if I'm too high, too low, or correct!")

    start = 1
    end = 100
    attempts = 0
    user_choice = int(input("Enter your choice: "))

    while start <= end:

        guess = (start + end) // 2
        attempts += 1

        print(f"User guess is {user_choice}")
        print(f"🤖 My guess is: {guess}")



        feedback = input("Is my guess (H)igh, (L)ow, or (C)orrect? ").lower()


        if feedback == "c":
            print(f"🎉 I guessed your number {guess} in {attempts} attempts!")
            break
        elif feedback == "h":
            end = guess - 1
        elif feedback == "l":
            start = guess + 1
        else:
            print("⚠️ Invalid input! Please enter 'H' for High, 'L' for Low, or 'C' for Correct.")


    if input("Play again? (yes/no): ").lower() == 'yes':
        computer_guess()
    else:
        print("Thanks for playing! Goodbye 👋")


def main():
    computer_guess()

if __name__ == "__main__":
    main()