# -*- coding: utf-8 -*-
"""Guess the Number Game (computer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tuewSORv_nQuB28YzSA2leJUiUL4Noh
"""

import random

def get_guess():
  print("🎯 Welcome to 'Guess the Number' Game!")
  print("I'm thinking of a number between 1 and 100...")

  number_to_guess = random.randint(1, 100)
  attempts = 0

  while True:
    try:
      guess = int(input("Enter your guess: "))
      attempts += 1

      if guess < number_to_guess:
        print("Too low! Try again.")
      elif guess > number_to_guess:
        print("Too high! Try again.")
      else:
        print(f"🎉 Correct! You guessed it in {attempts} attempts.")
        break
    except ValueError:
        print("Invalid input. Please enter a valid number.")

  if input("Do you want to play again? (yes/no): ").lower() == "yes":
    get_guess()
  else:
    print("Thanks for playing! Goodbye.")

def main():
  get_guess()
if __name__ == "__main__":
    main()