# -*- coding: utf-8 -*-
"""Hangman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaGyOeDHX1j82GbjvD-ZbcjRjiMDIBNa
"""

import random

def hangman():
  words = ["baber", "naseem", "haris", "saim", "kholi", "dhoni", "rizwan"]

  secret_word = random.choice(words)
  guessed_letters = []
  attempts = 6
  word_progress = ["_"] * len(secret_word)

  print("Welcome to Hangman!")
  print("Try to guess the cricketer name.")
  print(f"Word has {len(secret_word)} letters: {' '.join(word_progress)}")
  print(f"You have {attempts} attempts.\n")

  while attempts > 0 and "_" in word_progress:
    guess = input("Guess a letter: ").lower()

    if len(guess) != 1 or not guess.isalpha():
      print("Please enter a single letter (a-z).")
      continue

    if guess in guessed_letters:
      print(f"You've already guessed {guess}.")
      continue

    guessed_letters.append(guess)

    if guess in secret_word:
      for i in range(len(secret_word)):
        if secret_word[i] == guess:
          word_progress[i] = guess
          print(f"Correct! {guess} is in the word.")
    else:
      attempts -= 1
      print(f"Wrong guess! {guess} is not in the word")

    print("\nWord: " + " ".join(word_progress))
    print("Guessed letters: " + ", ".join(guessed_letters))
    print("Attempts left: " + str(attempts) + "\n")

    print_hangman(attempts)


  if "_" not in word_progress:
    print("Congratulations! You guessed the word: " + secret_word)
  else:
    print("Game over! The word was: " + secret_word)

def print_hangman(attempts):
  stages = ["""
        -----
        |   |
            |
            |
            |
            |
        --------
        """,
        """
        -----
        |   |
        O   |
            |
            |
            |
        --------
        """,
        """
        -----
        |   |
        O   |
        |   |
            |
            |
        --------
        """,
        """
        -----
        |   |
        O   |
       /|   |
            |
            |
        --------
        """,
        """
        -----
        |   |
        O   |
       /|\  |
            |
            |
        --------
        """,
        """
        -----
        |   |
        O   |
       /|\  |
       /    |
            |
        --------
        """,
        """
        -----
        |   |
        O   |
       /|\  |
       / \  |
            |
        --------
        """]
  print(stages[attempts])

def main():
  hangman()
if __name__ == "__main__":
    main()