# -*- coding: utf-8 -*-
"""Mad libs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_oA3p0bkTzpWiI0oV7GrmoLRruLtwym
"""

import random

def get_word(word_type):
    return input(f"{word_type}: ")

def jungle_story():
    print("\nJungle Adventure - Please provide the following words:")
    words = {
        'adjective': get_word("Adjective"),
        'noun': get_word("Noun"),
        'verb': get_word("Verb")
    }

    return f"""
    Deep in the {words['adjective']} jungle, I spotted a mysterious {words['noun']} hiding behind the bushes.
    As I got closer, it suddenly started to {words['verb']}!
    I couldn’t believe my eyes—it was the wildest adventure of my life.
    """

def school_story():
    print("\nSchool Drama - Please provide the following words:")
    words = {
        'adjective': get_word("Adjective"),
        'noun': get_word("Noun"),
        'verb': get_word("Verb")
    }

    return f"""
    Today was a {words['adjective']} day at school.
    During math class, a {words['noun']} rolled into the room and started to {words['verb']}!
    Everyone laughed, and even the teacher couldn't stop smiling.
    """

def main():
    print("Welcome to 3-Word Mad Libs!")
    print("Choose a story:")
    print("1. Jungle Adventure")
    print("2. School Drama")

    choice = input("Enter your choice (1 or 2): ")

    if choice == '1':
        story = jungle_story()
    elif choice == '2':
        story = school_story()
    else:
        print("Invalid choice. Random story selected for you!")
        story_func = random.choice([jungle_story, school_story])
        story = story_func()

    print("\nHere's your Mad Lib story:")
    print(story)

    if input("\nWould you like to play again? (yes/no): ").lower() == 'yes':
        main()
    else:
        print("Thanks for playing 3-Word Mad Libs! 😊")

if __name__ == "__main__":
    main()