# -*- coding: utf-8 -*-
"""Password Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHfquhSZ_oRd5dm84dPIg5-d0nA-PYG_
"""

import random
import string

def password_generater(lenght, use_upper, use_lower, use_digit, use_symbol):
    words = ""

    if use_upper:
        words += string.ascii_uppercase
    if use_lower:
        words += string.ascii_lowercase
    if use_digit:
        words += string.digits
    if use_symbol:
        words += string.punctuation

    if not words:
      print("Error: No character types selected.")


    password = "".join(random.choices(words, k=lenght))
    return password

def main():
     print("🔐 Welcome to the Python Password Generator 🔐\n")

     try:
      lenght = int(input("Enter the desired password length: "))
      if lenght <= 0:
        print("Error: Password length must be a positive integer.")
        return

      use_upper = input("Include uppercase letters? (y/n): ").lower() == "y"
      use_lower = input("Include lowercase letters? (y/n): ").lower() == "y"
      use_digit = input("Include digits? (y/n): ").lower() == "y"
      use_symbol = input("Include symbols? (y/n): ").lower() == "y"

      password = password_generater(lenght, use_upper, use_lower, use_digit, use_symbol)
      print("\nGenerated Password:", password)

     except ValueError:
      print("Error: Invalid input. Please enter a valid integer for the password length.")
if __name__ == "__main__":
    main()