# -*- coding: utf-8 -*-
"""Project 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ld8tp1yPsx_H3JtfY-KkD3pbBPXyJMSf
"""

import streamlit as st
import requests

API_KEY = st.secrets["API_KEY"]

FIND_URL = "https://api.spoonacular.com/recipes/findByIngredients"
INFO_URL = "https://api.spoonacular.com/recipes/{id}/information"


st.set_page_config(page_title="Recipe Finder", page_icon="🍳", layout="centered")


st.markdown("""
    <h1 style='text-align: center; color: #6c5ce7;'>🍳 Recipe Finder</h1>
    <p style='text-align: center; font-size: 18px; color: #636e72;'>Type your ingredients & discover recipes instantly!</p>
    """, unsafe_allow_html=True)


st.markdown("""
    <style>
    .stTextInput>div>div>input {
        border-radius: 10px;
        border: 2px solid #dfe6e9;
        padding: 12px;
        font-size: 16px;
    }
    .card {
        border-radius: 15px;
        background-color: #f1f2f6;
        padding: 20px;
        margin-bottom: 15px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        transition: 0.3s;
    }
    .card:hover {
        box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        background-color: #ffffff;
    }
    .footer {
        padding: 20px;
        text-align: center;
        color: #888;
        font-size: 14px;
        border-top: 1px solid #f1f1f1;
        margin-top: 40px;
    }
    </style>
    """, unsafe_allow_html=True)


ingredients = st.text_input("🔎 Enter ingredients (comma separated)", key="ingredients")


def get_recipes(ingredients):
    try:
        response = requests.get(
            f"{FIND_URL}?ingredients={ingredients}&number=5&apiKey={API_KEY}",
            timeout=10
        )
        if response.status_code == 200:
            return response.json()
        else:
            st.error("Failed to fetch recipes.")
            return []
    except requests.exceptions.Timeout:
        st.error("API timeout. Please check your internet or try again later.")
        return []


def get_recipe_details(recipe_id):
    response = requests.get(INFO_URL.format(id=recipe_id), params={"apiKey": API_KEY})
    if response.status_code == 200:
        return response.json()
    else:
        st.error("Could not load recipe details.")
        return None


if ingredients:
    recipes = get_recipes(ingredients)

    if recipes:
        st.markdown("### 🍽️ Recipes Found:")
        for recipe in recipes:
            with st.container():
                with st.expander(f"🍴 {recipe['title']}", expanded=False):
                    st.markdown(f"<div class='card'>", unsafe_allow_html=True)
                    st.image(f"https://spoonacular.com/recipeImages/{recipe['id']}-312x231.jpg", use_container_width=True)
                    full = get_recipe_details(recipe['id'])
                    if full:
                        st.markdown(f"**⏱️ Ready in:** {full['readyInMinutes']} minutes")
                        st.markdown(f"**🍽️ Servings:** {full['servings']}")
                        st.markdown("### 🧂 Ingredients:")
                        st.markdown("<ul>" + "".join(f"<li>{ing['original']}</li>" for ing in full["extendedIngredients"]) + "</ul>", unsafe_allow_html=True)
                        st.markdown("### 📋 Instructions:")
                        if full.get("instructions"):
                            st.markdown(full["instructions"])
                        else:
                            st.info("Instructions not available for this recipe.")
                    st.markdown("</div>", unsafe_allow_html=True)
    else:
        st.warning("No recipes found. Try different ingredients.")


st.markdown('<div class="footer">Created with ❤️ by Zohaib</div>', unsafe_allow_html=True)