# -*- coding: utf-8 -*-
"""Rock, paper, scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feT68tEFIwW0X-HDUXEYWtFnh2sibtRH
"""

import random

def rock_paper_scissor():
  print("Welcome to rock, paper, scissor game!")
  print("Game Rules:")
  print("1. Rock vs paper-> paper wins")
  print("2. Rock vs scissor-> Rock wins")
  print("3. paper vs scissor-> scissor wins")
  print("Enter 'quit' to exit the game.\n")

  choices = ['rock', 'paper', 'scissor']
  score = {'you': 0, 'computer': 0, 'ties': 0}

  while True:
    player_choice = input("Enter your choice (rock, paper, scissor): ").lower()

    if player_choice == "quit":
      print("Thanks for Playing!")
      break
    elif player_choice not in choices:
      print("Invalid choice. Please choose from 'rock', 'paper', or 'scissor'.")
      continue

    computer_choice = random.choice(choices)
    print(f"Computer choose: {computer_choice}")

    if computer_choice == player_choice:
      print("It's a tie!")
      score['ties'] += 1
    elif (player_choice == 'rock' and computer_choice == 'scissor') or \
         (player_choice == 'paper' and computer_choice == 'rock') or \
         (player_choice == 'scissor' and computer_choice == 'paper'):
      print("You win!")
      score['you'] += 1
    else:
      print("Computer wins!")
      score['computer'] += 1

    print(f"\nCurrent score - You: {score['you']}, Computer: {score['computer']}, Ties: {score['ties']}\n")

  print("Final score:")
  print(f"You: {score['you']}, Computer: {score['computer']}, Ties: {score['ties']}")

def main():
  rock_paper_scissor()
if __name__ == "__main__":
  main()