# -*- coding: utf-8 -*-
"""00_guess_my_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19GpsVc2tNuQHzYmi0ooSuR3AdyQxNuxr
"""

import random

def main():
  Comp = random.randint(1, 100)

  while True:
   guess = input("Enter a number (or press Enter to exit): ")


   if guess == "":
    print("Goodbye!")
    break

   if not guess.isdigit():
    print("Invalid input! Please enter a number.")
    continue

   user_num = int(guess)

   if user_num > Comp:
     print("Your guess is too high!")

   elif user_num < Comp:
      print("Your guess is too low!")
   else:
      print(f"Congratulations! The number was {Comp}")
      break

if __name__ == '__main__':
    main()