# -*- coding: utf-8 -*-
"""01_fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OQN6i_5rIJ0kbS4EIjdiCZlk_12erED
"""

MAX_VALUE : int = int(input("Enter a Number: "))

def fibonacci():
  a,b = 0,1

  while a < MAX_VALUE:
    print(a, end=" ")
    a,b = b, a+b
  print()

def main():
  fibonacci()
if __name__ == '__main__':
    main()