# -*- coding: utf-8 -*-
"""02_print_events.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v438tH-ORjNYjeKzZCHqJrmRU7qVeJZC
"""

def Even():
  for i in range(1, 20):
    print(i * 2, end=" ")


def main():
  Even()
if __name__ == '__main__':
    main()