# -*- coding: utf-8 -*-
"""03_wholesome_machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zj_59339Co58xOVWEV6nDaM7CAVVwTJ2
"""

Information : str = "I am capable of doing anything I put my mind to."

def Check_Inform():
  print(f"Please type the following affirmation: {Information}")
  user_response = input()

  while True:
    if user_response == "":
      print("Goodbye!")
      break

    if user_response != Information:
     print("That was not the affirmation!")

     print(f"Please type the following affirmation: {Information}")
     user_response = input()

    else:
     print("That's Right")
     break


def main():
  Check_Inform()
if __name__ == '__main__':
    main()