# -*- coding: utf-8 -*-
"""04_liftoff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18knFKqMkFb2x77TpI7v-lOhTHkn-aHLO
"""

def main():
  for i in range(10, 0, -1):
    print(i, end=" ")
  print("Liftoff")

if __name__ == '__main__':
    main()