# -*- coding: utf-8 -*-
"""05_double_it.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1515qWpfmaV9f7QvEIdHe9iKeyrMHErsX
"""

def main():
    current_val = int(input("Please enter a number: "))

    while current_val < 100:
      current_val = current_val * 2
      print(current_val, end=" ")

if __name__ == '__main__':
    main()