# -*- coding: utf-8 -*-
"""01_dicesimulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17c4ULCMZUOiSvxvv8-t0hpyeY0z6-_Yg
"""

import random
Num_Sides = 6

def roll_dice():
  dice1 = int(random.randint(1,Num_Sides))
  dice2 = int(random.randint(1,Num_Sides))
  Total = str(dice1 + dice2)
  print(f"The total value of dice1 and dice2 is {Total}")

def main():
  dice1 : int = 10
  print(f"The value of dice1 is {dice1}")
  roll_dice()
  roll_dice()
  roll_dice()
  print(f"The value of dice1 is {dice1}")

if __name__ == '__main__':
    main()