# -*- coding: utf-8 -*-
"""02_e=mc2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mZrKjR5YCuX96TUKTjZZHSL7-_e5bzV
"""

C : int = 299792458
def main():
 mass_Kg : float = float(input("Enter mass in kilos: \033[1;3m"))
 energy_joules = mass_Kg * (C ** 2)
 print(f"\033[0menergy_joules = {mass_Kg} * {C ** 2}")
 print(f"\033[0m{energy_joules} : Joules of energy")

if __name__ == '__main__':
    main()