# -*- coding: utf-8 -*-
"""03_feet_to_inches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Rv3PEB0NmOdp4SKCDVt0UR6BUsaMHG1
"""

Inches_in_Feet : float = 12
def main():
  Feet : float = float(input("Enter Number of Foot you walk: "))
  Inches : float = (Feet * Inches_in_Feet)
  print(f"The Total Foot you walk is {Inches} Inches")

if __name__ == '__main__':
    main()