# -*- coding: utf-8 -*-
"""04_pythagorean_theorem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTbU6_-g77kc_G3xHn4dlJyJTfm1m9XQ
"""

import math
def main():
   AB : float = float(input("Enter lenght of AB: \033[1;3m"))
   AC : float = float(input("\033[0mEnter lenght of AC: \033[1;3m"))

   BC : float = math.sqrt(AB**2 + AC**2)
   print(f"\033[0mThe Lenght of BC is \033[1;3m{BC}")
if __name__ == '__main__':
    main()