# -*- coding: utf-8 -*-
"""05_remainder_division.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sr6mXc7XTtna2By0mT00ZN5TQeg_wRDK
"""

def main():
    Divisible : int = int(input("Please enter a number to be divisible: \033[1;3m"))
    Divided : int = int(input("\033[0mPlease enter a number to be divided: \033[1;3m"))

    Q : int = Divisible // Divided
    R : int = Divisible % Divided
    print(f"\033[0mThe Result of this Division is \033[1;3m{Q} \033[0mwith a Reminder of \033[1;3m{R}")
if __name__ == '__main__':
    main()