# -*- coding: utf-8 -*-
"""06_rolldice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJ6MYclLjYOVy3Wkpd1k2FJl8l0WtaJl
"""

import random

Dice_Sides : int = 6
def main():
  dice1 : int = int(random.randint(1, Dice_Sides))
  dice2 : int = int(random.randint(1, Dice_Sides))

  Total : int = int(dice1 + dice2)

  print(f"The Dice have {Dice_Sides} Sides!")
  print(f"The result of dice1 is {dice1}!")
  print(f"The result of dice2 is {dice2}!")
  print(f"The Total of Dices is {Total}!")


if __name__ == '__main__':
    main()