# -*- coding: utf-8 -*-
"""06_seconds_in_year.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FW6ICBXe-xmoXAFT118ApfbYcXE86YSx
"""

D_in_Y : int = 365
H_in_D : int = 24
M_in_H : int = 60
S_in_M : int = 60

def main():
  Sec : int = (D_in_Y * H_in_D * M_in_H * S_in_M)
  print(f"There are {Sec} sec in a Year !")

  # Year : int = int(input("Enter the number of years: \033[1;3m"))  Optionally ! user se input le ga
  # Sec : int = (Year * D_in_Y * H_in_D * M_in_H * S_in_M )          usko convert karega seconds me
  # print(f"\033[0mThere are {Sec} sec in a Year !")                 aur phir usko print karega

if __name__ == '__main__':
    main()