# -*- coding: utf-8 -*-
"""07_tiny_mad_lib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcqmaamVF6OFJk0tuaWxCpv6YV7gAIIx
"""

Story_Sentence : str = "The old man walked through the dense forest, listening to the chirping birds and rustling leaves, until he found a"
def main():
   Adjective : str = input("Please type an adjective and press enter: \033[1;3m")
   Noun : str = input("\033[0mPlease type an Noun and press enter: \033[1;3m")
   Adverb : str = input("\033[0mPlease type an Adverb and press enter: \033[1;3m")

   print(f"\033[0m{Story_Sentence} \033[1;3m{Adjective} \033[1;3m{Noun} \033[1;3m{Adverb} !")
if __name__ == '__main__':
    main()