# -*- coding: utf-8 -*-
"""00_joke_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X12Ny0GVfbGaBST9X1lQL4PKZwNpAzUo
"""

Prompt : str = "What do you want? \033[34m"
Sorry : str = "\033[0mSorry! I only tell jokes"
Joke : str = "\033[0mHere is a joke for you! Panaversity GPT - Sophia is heading out to the grocery store. A programmer tells her: get a liter of milk, and if they have eggs, get 12. Sophia returns with 13 liters of milk. The programmer asks why and Sophia replies: 'because they had eggs'"

def main():

  user_input = input(Prompt.strip().lower())

  if "joke" in user_input:
    print(Joke)
  else:
    print(Sorry)

if __name__ == '__main__':
    main()