# -*- coding: utf-8 -*-
"""01_double_it.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_x7kqT0OtURfht2HOgRvt4SphyGkY1K
"""

def main():
    current_Val = int(input("Please enter a number: "))

    while current_Val < 100:
      current_Val = current_Val * 2
      print(current_Val, end=" ")

if __name__ == '__main__':
    main()