# -*- coding: utf-8 -*-
"""02_liftoff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6L2UZ5Ab0xvWWBDzkI9Rbit1T7juuXt
"""

def main():
  for num in range(10, 0 ,-1):
    print(num, end=" ")
  print("Liftoff!")
if __name__ == '__main__':
    main()