# -*- coding: utf-8 -*-
"""03_guess_my_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lx3H9OC3LqACZUBpgdaiJDFBs9EcXfRu
"""

import random

def main():
  user_num = int(input("please enter a number: "))
  comp_num = random.randint(0, 99)

  if user_num > comp_num:
    print(f"Your guess is too high! {user_num}")
  elif user_num < comp_num:
    print(f"Your guess is too low! {user_num}")
  elif user_num == comp_num:
    print(f"Congrates! The number was {user_num}")
  else:
    print("Invalid input! Please enter a number")

if __name__ == '__main__':
    main()