# -*- coding: utf-8 -*-
"""04_random_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhlU6FpZ9T1WLD6ATmp6PdNO5sZO5zI3
"""

import random

N_NUMBERS: int = 10
MIN_VALUE: int = 1
MAX_VALUE: int = 100

def main():
   for i in range(N_NUMBERS):
    print(random.randint(MIN_VALUE, MAX_VALUE), end=" ")
if __name__ == '__main__':
    main()