# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPtVrVV9A7YQH19C0Y2Wk7eqHXKTQ_gP
"""

import time
import matplotlib.pyplot as plt
import random

def binary_search_recursive(arr, target, left, right):
    if left > right:
        return -1
    mid = left + (right - left) // 2
    if arr[mid] == target:
        return mid
    elif arr[mid] < target:
        return binary_search_recursive(arr, target, mid + 1, right)
    else:
        return binary_search_recursive(arr, target, left, mid - 1)

def binary_search_iterative(arr, target):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = left + (right - left) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

def measure_time(func, arr, target):
    start = time.time()
    func(arr, target)
    return (time.time() - start) * 1000

def visualize_performance():
    sizes = [10**i for i in range(1, 6)]
    recursive_times, iterative_times = [], []

    for size in sizes:
        arr = sorted(random.sample(range(size * 10), size))
        target = random.choice(arr)

        recursive_time = measure_time(lambda a, t: binary_search_recursive(a, t, 0, len(a) - 1), arr, target)
        iterative_time = measure_time(binary_search_iterative, arr, target)

        recursive_times.append(recursive_time)
        iterative_times.append(iterative_time)

    plt.plot(sizes, recursive_times, label='Recursive', marker='o')
    plt.plot(sizes, iterative_times, label='Iterative', marker='s')
    plt.xlabel('Array Size')
    plt.ylabel('Execution Time (ms)')
    plt.xscale('log')
    plt.yscale('log')
    plt.legend()
    plt.title('Binary Search Performance Comparison')
    plt.grid(True)
    plt.show()

def main():
    arr = sorted(random.sample(range(1, 100), 20))
    target = random.choice(arr)

    print("Sorted Array:", arr)
    print("Target:", target)

    index_recursive = binary_search_recursive(arr, target, 0, len(arr) - 1)
    index_iterative = binary_search_iterative(arr, target)

    print(f"Recursive Binary Search Index: {index_recursive}")
    print(f"Iterative Binary Search Index: {index_iterative}")

    visualize_performance()

if __name__ == "__main__":
    main()