# -*- coding: utf-8 -*-
"""Bulk File Re-namer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJ2rrz-k3RfIQKMYZbqIwNnEm2ZhVI5v
"""

from genericpath import isfile
import os
import shutil

directory = input("Please enter your folder path: ")

prefix = input("Enter Prefix (press enter to skip): ")
suffix = input("Enter Suffix (press enter to skip): ")
replace_text = input("Enter Text to Replace (press enter to skip): ")
replace_with = input("Enter Text to Replace With (press enter to skip): ")
start_number = input("Enter Starting Number (press enter to skip): ")

start_number = int(start_number) if start_number.isdigit() else 1

backup_folder = os.path.join(directory, "backup_renamer") 

if os.path.exists(directory):
    files = sorted(os.listdir(directory))

    if not os.path.exists(backup_folder):
        os.makedirs(backup_folder)  

    for index, filename in enumerate(files, start=start_number):
        file_path = os.path.join(directory, filename)
        if os.path.isfile(file_path):
            name, ext = os.path.splitext(filename)
            
            shutil.copy(file_path, os.path.join(backup_folder, filename))

            
            if replace_text:
                name = name.replace(replace_text, replace_with)

            new_name = f"{prefix}{name}{suffix}{ext}"
            new_path = os.path.join(directory, new_name)

           
            if not os.path.exists(new_path):
                os.rename(file_path, new_path)
            else:
                print(f"File {new_name} already exists. Skipping renaming.")

    print("\n✅ Files renamed successfully!")

else:
    print("Directory not found. Please provide a valid path.")


def undo_rename():
    if not os.path.exists(backup_folder):
        print("No backup folder found. Undo is not possible.")
        return

    for backup_file in os.listdir(backup_folder):
        original_file = os.path.join(backup_folder, backup_file)
        new_path = os.path.join(directory, backup_file)

        
        if os.path.exists(new_path):
            os.remove(new_path)

        shutil.move(original_file, new_path)  

    shutil.rmtree(backup_folder)  
    print("\n✅ Undo successful! Files restored.")


def main():
    undo_option = input("\nDo you want to undo the rename? (yes/no): ")
    if undo_option.lower() == "yes":
        undo_rename()

if __name__ == '__main__':
    main()

