# -*- coding: utf-8 -*-
"""Country Information Cards.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6-8KoTdBzQaCN9hh18bAQr8oZe46j2B
"""

import streamlit as st
import requests

st.set_page_config(page_title="🌍 Country Info Cards", layout="centered")

# Style block
st.markdown("""
    <style>
    html, body, [class*="css"] {
        font-family: 'Segoe UI', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
    }

    .main-card {
        animation: fadeInUp 1s ease-in-out;
        background: white;
        border-radius: 16px;
        padding: 30px;
        box-shadow: 0 8px 30px rgba(0, 0, 0, 0.1);
        margin-top: 40px;
        transform-style: preserve-3d;
        transition: transform 0.6s ease;
    }

    .main-card:hover {
        transform: rotateY(10deg) scale(1.05);
        box-shadow: 0 15px 50px rgba(0, 0, 0, 0.2);
    }

    .flag-img {
        border-radius: 10px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        width: 100%;
        max-width: 240px;
        height: auto;
        margin-bottom: 20px;
        animation: zoomIn 0.6s ease;
    }

    .country-title {
        font-size: 2.2rem;
        font-weight: 700;
        margin-bottom: 10px;
        color: #222;
        transition: color 0.3s ease;
    }

    .country-info {
        font-size: 1.1rem;
        color: #555;
        line-height: 1.6;
        transition: all 0.3s ease;
    }

    .main-card:hover .country-title {
        color: #b88e2f;
    }

    .main-card:hover .country-info {
        color: #222;
    }

    @keyframes fadeInUp {
        from { opacity: 0; transform: translateY(40px); }
        to { opacity: 1; transform: translateY(0); }
    }

    @keyframes zoomIn {
        from { opacity: 0; transform: scale(0.9); }
        to { opacity: 1; transform: scale(1); }
    }
    </style>
""", unsafe_allow_html=True)

st.title("🌍 Country Info Cards")

# Caching and safe loading of countries
@st.cache_data
def load_countries():
    url = "https://restcountries.com/v3.1/all"
    try:
        res = requests.get(url, timeout=10)
        res.raise_for_status()
        return sorted([c["name"]["common"] for c in res.json()])
    except requests.exceptions.RequestException as e:
        st.error(f"⚠️ Could not load country list: {e}")
        return []

# Fetch individual country data safely
def get_country_data(country_name):
    url = f"https://restcountries.com/v3.1/name/{country_name}"
    try:
        res = requests.get(url, timeout=10)
        res.raise_for_status()
        return res.json()[0]
    except requests.exceptions.RequestException as e:
        st.error(f"⚠️ Could not fetch data for {country_name}: {e}")
        return None

# Load country list and show selector if available
country_list = load_countries()
if country_list:
    country = st.selectbox("Select a country", country_list, index=country_list.index("France"))

    data = get_country_data(country)

    if data:
        st.markdown('<div class="main-card">', unsafe_allow_html=True)

        st.image(data["flags"]["png"], use_container_width=True, caption=data["name"]["common"])

        st.markdown(f"""
            <div class="country-title">{data['name']['common']}</div>
            <div class="country-info">
                <strong>Capital:</strong> {data.get('capital', ['N/A'])[0]}<br>
                <strong>Region:</strong> {data['region']}<br>
                <strong>Population:</strong> {data['population']:,}<br>
                <strong>Languages:</strong> {', '.join(data.get('languages', {}).values())}<br>
                <strong>Currency:</strong> {', '.join([v['name'] for v in data.get('currencies', {}).values()])}<br>
                <strong>Timezone:</strong> {', '.join(data.get('timezones', []))}<br>
            </div>
        """, unsafe_allow_html=True)

        st.markdown('</div>', unsafe_allow_html=True)
else:
    st.warning("No countries available to select. Please check your internet connection or try again later.")
