# -*- coding: utf-8 -*-
"""Data Driven Web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wBWAczl2xaLMAF9SWZgfr_b5KIsB4Cnz
"""

import streamlit as st
import pandas as pd

st.title('CSV Data Viewer & Analyzer')


uploaded_file = st.file_uploader("Upload a CSV file", type=["csv"])


if uploaded_file is not None:

    df = pd.read_csv(uploaded_file)


    st.write("Data Preview:")
    st.dataframe(df.head())


    if st.checkbox("Show Summary Statistics"):
        st.write("Summary Statistics:")
        st.write(df.describe())


    st.write("Data Visualizations:")
    if st.button('Show Histograms'):
        for column in df.select_dtypes(include=['float64', 'int64']).columns:
            st.subheader(f"Histogram of {column}")
            st.bar_chart(df[column])

    