# -*- coding: utf-8 -*-
"""QR code encoder / decoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d12BVf6mBYIg-TREZCpZ3hAS2JNBAMzB
"""

import qrcode
import cv2
import os

try:
  from google.colab.patches import cv2_imshow
  in_colab = True
except ImportError:
  in_colab = False

def encoder(data, filename = "qr_code.png"):
  qr = qrcode.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=10, border=4)
  qr.add_data(data)
  qr.make(fit=True)
  img = qr.make_image(fill_color="black", back_color="white")
  img.save(filename)
  print(f"✅ QR Code saved as {filename}")

  if in_colab:
    cv2_imshow(cv2.imread(filename))
  else:
    cv2.imshow("QR Code", cv2.imread(filename))
    cv2.waitKey(0)
    cv2.destroyAllWindows()

def decoder(filename):
  if not os.path.exists(filename):
    print(f"❌ File {filename} not found")
    return

  img = cv2.imread(filename)
  detector = cv2.QRCodeDetector()
  data, bbox, _ = detector.detectAndDecode(img)

  if data:
    print(f"✅ QR Code decoded: {data}")
  else:
    print("❌ QR Code not found")

def main():
  choice = input("What do you want encode or decode? ").strip().lower()

  if choice == "encode":
    data = input("Enter data to encode: ")
    filename = input("Enter filename to save QR code: ")
    encoder(data, filename)
  elif choice == "decode":
    filename_to_decode = input("Enter filename to decode QR code: ")
    decoder(filename_to_decode)
  else:
    print("Invalid Input!")
if __name__ == "__main__":
    main()