# -*- coding: utf-8 -*-
"""Tic-Tac-Toe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Go6UipUvOXE_8fZ6dYZ9soTclwyXTwN0
"""

board = [" " for _ in range(9)]

def print_board(current_player, Players):
    print("\n")
    print(f" {board[0]} | {board[1]} | {board[2]} ")
    print("---+---+---")
    print(f" {board[3]} | {board[4]} | {board[5]} ")
    print("---+---+---")
    print(f" {board[6]} | {board[7]} | {board[8]} ")
    print("\n")

def check_win(Player):
    win_conditions = [
        [0,1,2], [3,4,5], [6,7,8],
        [0,3,6], [1,4,7], [2,5,8],
        [0,4,8], [2,4,6]
    ]
    for condition in win_conditions:
        if board[condition[0]] == board[condition[1]] == board[condition[2]] == Player:
            return True
    return False

def check_tie():
    return " " not in board

def player_move(Player, Player_name):
    while True:
        try:
            move = int(input(f"{Player_name} ({Player}), choose your move (1-9): ")) - 1
            if 0 <= move <= 8 and board[move] == " ":
                board[move] = Player
                break
            else:
                print("Invalid move. Try again!")
        except ValueError:
            print("Please enter a number between 1 and 9.")

def main():
    Player_1 = input("Enter Player 1's name: ")
    Player_2 = input("Enter Player 2's name: ")

    Players = {"X": Player_1, "O": Player_2}
    current_player = "X"

    while True:
        print_board(current_player, Players)
        player_move(current_player, Players[current_player])

        if check_win(current_player):
            print_board(current_player, Players)
            print(f"🎉 {Players[current_player]} ({current_player}) wins! 🎉")
            break
        elif check_tie():
            print_board(current_player, Players)
            print("It's a tie!")
            break

        current_player = "O" if current_player == "X" else "X"

if __name__ == "__main__":
    main()