# -*- coding: utf-8 -*-
"""Weather Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XJ7eS2GPqHmCcCiUkic5wV4VN2IdjQt
"""

import requests

API_KEY = "bff80907baab33ab50f3fcc15e4414b5"
BASE_URL = "http://api.openweathermap.org/data/2.5/weather"


def get_weather_data(city):
  params = {
      'q' : city,
      'appid' : API_KEY,
      'units' : 'metric'
  }

  response = requests.get(BASE_URL, params=params)
  data = response.json()

  if response.status_code == 200:
      print(f"\n🌤 Weather in {data['name']}, {data['sys']['country']}:")
      print(f"Temperature: {data['main']['temp']}°C")
      print(f"Humidity: {data['main']['humidity']}%")
      print(f"Description: {data['weather'][0]['description'].capitalize()}")
  else:
      print("❌ City not found or API error.")


def main():
  while True:
    city = input("Enter a city name or (Press enter to skip): ").strip()

    if city == "":
      break
    else:
      get_weather_data(city)
if __name__ == "__main__":
  main()