# -*- coding: utf-8 -*-
"""00_count_nums.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RP4eYhIRlJyZxIohErxNraz7y0QP5Wv_
"""

def count_numbers():
  Number_Count = {}

  while True:
    num = input("\033[0mEnter a number or Press enter to exit: \033[34m")

    if num == "":
      break
      print("\033[0mGoodBye!")

    if num.isdigit():
      num = int(num)
      Number_Count[num] = Number_Count.get(num, 0) + 1

  return Number_Count

def main():

  count = count_numbers()
  for number, count in sorted(count.items()):
    print(f"\033[0m{number} appears {count} {'times' if count > 1 else 'time'}")

if __name__ == '__main__':
    main()