# -*- coding: utf-8 -*-
"""01_phonebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFTBnQ7irbcO1V1ebrdN-BVnotXPC8YE
"""

def add_contact(phonebook):
    name = input("Enter contact name: ").strip()
    number = input("Enter phone number: ").strip()

    if name and number.isdigit():
        phonebook[name] = number
        print(f"✅ {name} added successfully!")
    else:
        print("❌ Invalid input. Please enter a valid name and number.")

def search_contact(phonebook):
    name = input("Enter name to search: ").strip()

    if name in phonebook:
        print(f"📞 {name}: {phonebook[name]}")
    else:
        print(f"❌ {name} not found.")

def display_contacts(phonebook):
    if phonebook:
        print("\n📖 Phonebook Contacts:")
        for name, number in phonebook.items():
            print(f"📞 {name}: {number}")
    else:
        print("📭 Phonebook is empty.")

def main():
    phonebook = {}

    while True:
        print("\n📞 PHONEBOOK MENU")
        print("1️⃣ Add Contact")
        print("2️⃣ Search Contact")
        print("3️⃣ Display All Contacts")
        print("4️⃣ Exit")

        choice = input("Choose an option: ").strip()

        if choice == "1":
            add_contact(phonebook)
        elif choice == "2":
            search_contact(phonebook)
        elif choice == "3":
            display_contacts(phonebook)
        elif choice == "4":
            print("👋 Exiting Phonebook. Goodbye!")
            break
        else:
            print("❌ Invalid choice. Please select a valid option.")

if __name__ == '__main__':
    main()