# -*- coding: utf-8 -*-
"""02_pop_up_shop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTqHH7bx0PFWHeX8mtNFRFpVQ3_016Qq
"""

def main():
   fruit_shop = {"Banana" : 2, "Apple" : 4, "Kiwi" : 2.5, "Mango" : 5, "Strawberry" : 15}

   Total_price = 0
   for fruit_name in fruit_shop:
    price = fruit_shop[fruit_name]
    fruit_bought = int(input(f"\033[0mHow many {fruit_name} do you want to purchase: \033[1;3m"))
    Total_price += (price * fruit_bought)
   print(f"\033[0mThe total price of fruits is {Total_price}")
if __name__ == '__main__':
    main()