# -*- coding: utf-8 -*-
"""03_powerful_passwords.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zM4cp6otg9JrnBD0KMvZ5ASTofACNTa4
"""

import hashlib

def hash_password(Password):
  return hashlib.sha256(Password.encode()).hexdigest()

Stored_login = {
      "User@gmail.com" : hash_password("User123"),
      "Memon@gmail.com" : hash_password("Memon123"),
      "Admin@gmail.com" : hash_password("Admin123")
  }

def login(Password_to_check, email):

  hashed_password = hash_password(Password_to_check)
  return Stored_login.get(email) == hashed_password

def main():
    email = input("Enter your email: ")
    password = input("Enter your password: ")

    if login(password, email):
      print("✅ Login successful! 🎉")
    else:
      print("❌ Incorrect email or password. Try again!")
if __name__ == '__main__':
    main()