# -*- coding: utf-8 -*-
"""00_choosing_returns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MN-dnh9l0hA8JBJsn7dk6n8xuzhkrMQM
"""

ADULT_AGE : int = 18

def Is_Adult(Age: int):
  if Age > ADULT_AGE:
    return True


  return False

def main():
  Age = int(input("Enter your age: \033[1;3m"))
  print(f"\033[0m{Is_Adult(Age)}")
if __name__ == '__main__':
    main()