# -*- coding: utf-8 -*-
"""01_greetings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUIiBxnLsChHetwtDhFyV6bG3oEWbhbG
"""

def greet(name):
  print(f"\033[0mHow are you, {name}!")

def main():
  name = input("Enter your name: \033[1;3m")
  greet(name)

if __name__ == '__main__':
    main()