# -*- coding: utf-8 -*-
"""02_in_range.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_CGvC-cFs-3aLby_bLuccYNrimf7IA-
"""

def in_range(num, low, high):
  if num >= low and num <= high:
    return True

  return False

def main():
  num = int(input("Enter a number: \033[1;3m"))
  low = int(input("\033[0mEnter low value: \033[1;3m"))
  high = int(input("\033[0mEnter high value: \033[1;3m"))
  print(f"\033[0m{in_range(num, low, high)}")

if __name__ == '__main__':
    main()