# -*- coding: utf-8 -*-
"""03_in_stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RG9jH0amgkx5-wWmwmIDz--LxGxeAyZ2
"""

Inventory = {
    "apple": 50,
    "banana": 30,
    "pear": 1000,
    "orange": 25,
    "grape": 0
}

def num_in_stock(fruit: str) -> int:
    return Inventory.get(fruit.lower(), 0)

def main():

    fruit = input("Enter a fruit: \033[1;3m").strip().lower()
    stock = num_in_stock(fruit)

    if stock > 0:
      print(f"\033[0mThis fruit is in stock! Here is the stock: {stock}")
    else:
      print("\033[0mThis fruit is not in stock.")
if __name__ == '__main__':
    main()