# -*- coding: utf-8 -*-
"""04_multiple_returns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMp65tDbkQ58WNepHDfAXj5OxcK9_j7K
"""

def get_user_data():
  F_Name = input("What is your first name? ")
  L_Name = input("What is your Last name? ")
  Email = input("What is your email address? ")

  return F_Name, L_Name, Email

def main():

  user_data = get_user_data()
  print(f"Recieved the following user data: {user_data}")

if __name__ == '__main__':
    main()