# -*- coding: utf-8 -*-
"""05_subtract_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8V0-_7slfU2k5Cy3QDYO4PihvH1iHmQ
"""

def subtract_seven(num: int):
  remind = num - 7
  print(remind)

def main():
   num = int(input("Enter a number to subtract from 7: "))
   subtract_seven(num)

if __name__ == '__main__':
    main()