# -*- coding: utf-8 -*-
"""00_averages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVziB9vlDhFHmAFcYaGxaypwXO6VKcZn
"""

def average(a, b):

  Average = (a + b) / 2
  print(Average)

def main():
  a = int(input("Enter your first number: "))
  b = int(input("Enter your second number: "))
  average(a, b)
if __name__ == '__main__':
    main()