# -*- coding: utf-8 -*-
"""02_count_even.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1240oltbMMDjMLsZtaZLwi8Drg_huqJL6
"""

def even_count():
  List = []

  while True:
    User_Num = input("Enter an integer or press enter to stop: ")
    if User_Num == "":
      break
    try:
      User_Num = int(User_Num)
      List.append(User_Num)
    except ValueError :
      print("Invalid input. Please enter an integer.")


  even_count = sum(1 for num in List if num % 2 == 0)
  print(f"Number of even numbers: {even_count}")


def main():
   even_count()
if __name__ == '__main__':
    main()