# -*- coding: utf-8 -*-
"""04_double.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYBvCYTQ-6GUoIAJUEOLipxnQUaytDpW
"""

def double(number):
  return number * 2

def main():
    number = int(input("Enter a number: \033[1;3m"))
    double_val = double(number)
    print(f"\033[0mDouble that is {double_val}")
if __name__ == '__main__':
    main()