# -*- coding: utf-8 -*-
"""05_get_name.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGLHbBN02SceqgBoYtauT5MEpw6clMns
"""

def get_name():
  name = input("Enter your name: ")
  return name

def main():
    my_name = get_name()
    print(f"Hello, {my_name}!")
if __name__ == '__main__':
    main()