# -*- coding: utf-8 -*-
"""06_is_odd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khWj8z6ar5-UJnf5FcvW6P6ittVciJ9R
"""

def odd(num: int):
  check = num % 2 == 1
  return check

def main():
    for num in range(1, 20):
      if odd(num):
        print(f"{num}:This is odd!")
      else:
        print(f"{num}:This is even!")
if __name__ == '__main__':
    main()