# -*- coding: utf-8 -*-
"""07_print_divisor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8_Kbz0KjRpC_9kc_kb_xcgJLhy8jI5S
"""

def divisor(val: int):
  divisor = [num for num in range(1, val + 1) if val % num == 0]
  print(f"Here are the divisors of {val}: {divisor}")

def main():
   val = int(input("Enter a number: \033[34m"))
   print("\033[0m", end="")
   divisor(val)
if __name__ == '__main__':
    main()