# -*- coding: utf-8 -*-
"""08_print_multiple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fS3FWCwNQFMsNR69FK6y5yVWsX95wP9S
"""

def print_multiple_message(message: str, number:int):
  for i in range(number):
    print(message)



def main():
   message = input("Please type a message: \033[34m")
   number = int(input("\033[0mEnter a number of times to repeat your message: \033[34m"))

   print_multiple_message(message, number)
if __name__ == '__main__':
    main()