# -*- coding: utf-8 -*-
"""09_sentence_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewMrjkg19rbx572gBp3hHLWdZ6EVqQtx
"""

def make_sentence(word, speech):
  if speech == 0:
    print(f"I am excited to add this {word} to my vast collection of them!")
  elif speech == 1:
    print(f"It's so nice outside today it makes me want to {word}!")
  elif speech == 2:
    print(f"Looking out my window, the sky is big and {word}!")
  else:
    print("Part of speech must be 0, 1, or 2! Can't make a sentence.")

def main():

 word = input("Please type a noun, verb or adjective: \033[34m")
 print("\033[0mIs this a noun, verb, or adjective?")
 speech = int(input("\033[0mType 0 for noun, 1 for verb, 2 for adjective: \033[34m"))
 print("\033[0m", end="")
 make_sentence(word, speech)

if __name__ == '__main__':
    main()