# -*- coding: utf-8 -*-
"""10_print_ones_digit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNm50Noc8uROZ6rbx8SvOBI7AtkuX-YP
"""

def print_one_digit(num: int):
  one_digit = num % 10
  print(f"The ones digit is {one_digit}")
def main():
   num = int(input("Enter a number: \033[34m"))
   print("\033[0m", end="")
   print_one_digit(num)
if __name__ == '__main__':
    main()