# -*- coding: utf-8 -*-
"""Control Flow for Console.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XM3GdIZ7nZpCAgbfNAusXnmVH6zRJAkK
"""

import random

def get_user_guess():
  while True:
    guess = input("Do you think your number is higher or lower than the computer's? (higher/lower): ").strip().lower()
    if guess in ["higher", "lower"]:
      return guess
    print("Please enter either 'higher' or 'lower'.")

def play_game(Round_Num):
   score = 0
   print("Welcome to the High-Low Game!")
   print("--------------------------------")

   for Round_Num in range(1, Round_Num + 1):
     user_num = random.randint(1, 100)
     comp_num = random.randint(1, 100)

     print(f"Round {Round_Num}")
     print(f"Your number is {user_num}")

     user_guess = get_user_guess()

     if (user_guess == "higher" and user_num > comp_num) or (user_guess == "lower" and user_num < comp_num):
       print(f"You were right! The computer's number was {comp_num}")
       score += 1
     else:
        print(f"Aww, that's incorrect. The computer's number was {comp_num}")

     print(f"Your score is now {score}\n")

   print(f"Thanks for playing!")
   if score == Round_Num :
    print("Wow! You played perfectly!")
   elif score >= Round_Num // 2:
    print("Good job, you played really well!")
   else:
    print("Better luck next time!")



def main():
    Round_Num = 5
    play_game(Round_Num)



if __name__ == "__main__":
    main()