# -*- coding: utf-8 -*-
"""Intro to Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eO4_jjUEY-IK7aL2en8YjACfhoGGJ_Pu
"""

def mars_weight(Earth_Weight):
  return round(Earth_Weight * 0.378, 2)

def all_Planets():
  Planet_Gravity = {
      "mercury": 0.376,
      "venus" : 0.889,
      "jupiter" : 2.36,
      "saturn" : 1.081,
      "uranus" : 0.815,
      "neptune" : 1.14,
      "earth" : 1.0}

  Earth_Weight = float(input("Enter a weight on Earth: "))
  planet = input("Enter a planet: ").strip().lower()

  if planet == "mars":
    planet_weight = mars_weight(Earth_Weight)
  elif planet in Planet_Gravity:
    planet_weight = round(Earth_Weight * Planet_Gravity[planet], 2)
  else:
    print("Invalid planet name!")

  print(f"The equivalent weight on {planet}: {planet_weight}")


def main():
    all_Planets()

if __name__ == "__main__":
    main()