# -*- coding: utf-8 -*-
"""Lists and Dicts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gA26L0ugGklh-JVm70XPm-bepSLVQK8G
"""

def access_element(List, index):
  return List[index] if 0 <= index < len(List) else "Index out of range!"


def modifying_element(List, index, new_value):
  if 0 <= index < len(List):
    List[index] = new_value
    return "Updated successfully!"
  return "Index out of range!"

def slicing_List(List, Start_index, End_index):
  return List[Start_index:End_index] if 0 <= Start_index < End_index <= len(List) else "Invalid range!"

def play_game():
  game_list = [2, "Mango", "First", True, "Flower", 20]
  while True:
    print(f"\nCurrent List: {game_list}\n")
    choice = input("Select an operation:\n1. Access an element\n2. Modify an element\n3. Slice the list\n4. Exit\nYour choice: ")

    if choice == "1":
      print(f"Element:", access_element(game_list, index = int(input("Enter index:"))))
    elif choice == "2":
      print(f"Modifying element:", modifying_element(game_list, index=int(input("Enter index: ")),new_value = input("Enter new Value: ")))
    elif choice == "3":
      print(f"Slicing list:", slicing_List(game_list, Start_index=int(input("Enter start index: ")), End_index=int(input("Enter end index: "))))
    elif choice == "4":
      print("Exiting...")
      break
    else:
      print("Invalid choice, please select a valid option.")

def main():
  play_game()


if __name__ == "__main__":
    main()