# -*- coding: utf-8 -*-
"""01_print_events.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UY37eEpsim3YKqZImxcpKLhLMzZgAXiP
"""

Number = 20

def main():

 for num in range(Number):
    print(num*2)

if __name__ == '__main__':
    main()