# -*- coding: utf-8 -*-
"""02_international_voting_age.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVO4uGHFvJiTYA8IU8sSI-yEvsiWRM7H
"""

Peturksbouipo_Age : int = 20
Stanlau_Age : int = 25
Mayengua_Age : int = 48

def voting_age(Age_input):

  if Age_input >= Peturksbouipo_Age:
    print(f"\033[0mYour age is {Age_input}! you can vote in Peturksbouipo, where the voting age is {Peturksbouipo_Age}.")
  else:
    print(f"\033[0mYour age is {Age_input}! you cannot vote in Peturksbouipo, where the voting age is {Peturksbouipo_Age}.")


  if Age_input >= Stanlau_Age:
    print(f"\033[0mYour age is {Age_input}! you can vote in Stanlau, where the voting age is {Stanlau_Age}.")
  else:
    print(f"\033[0mYour age is {Age_input}! you cannot vote in Stanlau, where the voting age is {Stanlau_Age}.")


  if Age_input >= Mayengua_Age:
    print(f"\033[0mYour age is {Age_input}! you can vote in Mayengua, where the voting age is {Mayengua_Age}.")
  else:
    print(f"\033[0mYour age is {Age_input}! you cannot vote in Mayengua, where the voting age is {Mayengua_Age}.")


def main():

  Age_input = int(input("What is your age: \033[34m"))

  voting_age(Age_input)


if __name__ == '__main__':
    main()