# -*- coding: utf-8 -*-
"""03_leap_year.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhXGoPGzbm-qwkxa3JKjwUyCMzC2ceoH
"""

def is_leap_year(Year):
  if (Year % 4 == 0 and Year % 100 != 0) or (Year % 400 == 0):
    return True
  return False

def main():
   Year = int(input("Enter a year to check it's leap or not: "))
   if is_leap_year(Year):
    print("That's a leap year!")
   else:
    print("That's not a leap year")
if __name__ == '__main__':
    main()