# -*- coding: utf-8 -*-
"""04_tall_enough_to_ride.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXRNVje9G3_IBJlyYp33a2iMkECQhmly
"""

MINIMUM_HEIGHT = 50

def tall_enough(Height):
    if Height >= MINIMUM_HEIGHT:
      print("\033[0mYou're tall enough to ride!")
    else:
      print("\033[0mYou're not tall enough to ride, but maybe next year!")


def main():
    while True:
      Height = input("\033[0mHow tall are you? (Press Enter to quit): \033[1;3m")

      if Height == "":
        print("\033[0mGoodBye!")
        break

      try:
        Height = float(Height)
        tall_enough(Height)
      except ValueError:
        print("Invalid input. Please enter a valid number.")

if __name__ == '__main__':
    main()