# -*- coding: utf-8 -*-
"""05_random_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITECgjtiGB65_PBn8MyV4KIRb4rUPCCO
"""
import random

DIGITS_NUMBER : int = 10
START_VALUE : int = 1
END_VALUE : int = 100

def generate_random_numbers():
  for i in range(DIGITS_NUMBER):
    value = random.randint(START_VALUE, END_VALUE)
    print(value, end=" ")

def main():
  generate_random_numbers()

if __name__ == '__main__':
  main()
