# -*- coding: utf-8 -*-
"""01_add_many_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xN4A9LXlWHKvzZaJAnHaM9xmX_TsPFkO
"""

def Sum_Num(Numbers):
  return sum(Numbers)

def main():

  my_list= [25, 39, 47, 86, 5]
  print(Sum_Num(my_list))

if __name__ == '__main__':
    main()