# -*- coding: utf-8 -*-
"""02_double_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqfFgStC4EBV58uxJZcUpvQC3VoGQJ2o
"""

def main():
  my_list : list[int] = [8, 5, 3, 7, 9]

  for item in range(len(my_list)):
    element = my_list[item]
    my_list[item] = element * 2
  print(my_list)

if __name__ == '__main__':
    main()