# -*- coding: utf-8 -*-
"""04_flowing_with_data_structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Txh85VnAIAOD18CFGhRN7rAAm74xk4Sl
"""

def make_Copies(my_list, message):
  for i in range(3):
    my_list.append(message)

def main():
   message : str = input("Write a message to make its copy: \033[1;3m")
   my_list = []
   print(f"\033[0mBefore: {my_list}")
   make_Copies(my_list , message)
   print(f"\033[0mafter: {my_list}")
if __name__ == '__main__':
    main()