# -*- coding: utf-8 -*-
"""05_get_first_element.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V4mXrOCdWzuiGex-5B2SysU4P6ik0sK
"""

def get_first_element(first):
  print(first[0])
  print(first)

def get_list_item():
  first = []
  data = input("Enter an element of the list or press enter to stop!")
  while data != "":
    first.append(data)
    data = input("Enter an element of the list or press enter to stop!")
  return first

def main():

   st = get_list_item()
   get_first_element(st)

if __name__ == '__main__':
    main()