# -*- coding: utf-8 -*-
"""06_get_last_element.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvoeDhcEds9du42g2fx3vmpsXExetyzW
"""

def get_last_element(last):
  print(last[-1])
  print(last)

def get_list_item():
  last = []
  data = input("Enter an element of the list or press enter to stop!")
  while data != "":
    last.append(data)
    data = input("Enter an element of the list or press enter to stop!")
  return last

def main():

   st = get_list_item()
   get_last_element(st)

if __name__ == '__main__':
    main()