# -*- coding: utf-8 -*-
"""07_get_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYj5azW0hhgvTkAN_Kj3jHbJozawjZyZ
"""

def main():
   my_list = []

   data = input("Enter a value or press enter: \033[34m")
   while data!= "":
      my_list.append(data)
      data = input("\033[0mEnter a value or press enter: \033[34m")
   print(f"\033[0m{my_list}")
if __name__ == '__main__':
    main()