# -*- coding: utf-8 -*-
"""08_shorten.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvBU7PtrGG2iy305i8nJ5sZLrDpMeoFJ
"""

Max_Lenght = 3

def Shorten(List):
  while len(List) > Max_Lenght:
    removed_item = List.pop()
    print(removed_item)

def main():
    my_List = [10, 40, 50, 90,20]
    Shorten(my_List)
    print(my_List)
if __name__ == '__main__':
    main()